"""add analytics tables

Revision ID: 1bf5618824b1
Revises: 868d1a7377f7
Create Date: 2026-02-12 19:24:31.323392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf5618824b1'
down_revision: Union[str, Sequence[str], None] = '868d1a7377f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Integer(), nullable=True),
    sa.Column('top_questions', sa.JSON(), nullable=True),
    sa.Column('allergen_inquiries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_chat_analytics_id'), 'chat_analytics', ['id'], unique=False)
    op.create_table('upsell_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('original_item_id', sa.Integer(), nullable=False),
    sa.Column('suggested_items', sa.JSON(), nullable=True),
    sa.Column('accepted_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['original_item_id'], ['menuitems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_upsell_analytics_id'), 'upsell_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upsell_analytics_id'), table_name='upsell_analytics')
    op.drop_table('upsell_analytics')
    op.drop_index(op.f('ix_chat_analytics_id'), table_name='chat_analytics')
    op.drop_table('chat_analytics')
    # ### end Alembic commands ###
