"""add calories to menuitems

Revision ID: 3354bee06b92
Revises: 5a81aac9ffd3
Create Date: 2026-05-08 14:05:51.164788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3354bee06b92'
down_revision: Union[str, Sequence[str], None] = '5a81aac9ffd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menuitems', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menuitems', 'calories')
    # ### end Alembic commands ###
