"""add items_rejected_count to chat_history

Revision ID: 5a81aac9ffd3
Revises: cb1a80b8a402
Create Date: 2026-04-14 20:17:07.714016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a81aac9ffd3'
down_revision: Union[str, Sequence[str], None] = 'cb1a80b8a402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('items_rejected_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'items_rejected_count')
    # ### end Alembic commands ###
