"""add_extracted_allergens_to_chat_history

Revision ID: 62c4f8a92fbe
Revises: bcf9189609df
Create Date: 2026-02-21 23:03:54.895152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62c4f8a92fbe'
down_revision: Union[str, Sequence[str], None] = 'bcf9189609df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('extracted_allergens', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'extracted_allergens')
    # ### end Alembic commands ###
