"""make customer_id nullable in sessions

Revision ID: 868d1a7377f7
Revises: b3f7c89a4d21
Create Date: 2026-02-09 19:58:10.504082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '868d1a7377f7'
down_revision: Union[str, Sequence[str], None] = 'b3f7c89a4d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_profiles_customer_id'), table_name='customer_profiles')
    op.create_index(op.f('ix_customer_profiles_id'), 'customer_profiles', ['id'], unique=False)
    op.drop_constraint(op.f('customer_profiles_customer_id_fkey'), 'customer_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'customer_profiles', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_customer_sessions_customer_id'), table_name='customer_sessions')
    op.drop_constraint(op.f('fk_customer_sessions_customer_id'), 'customer_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'customer_sessions', 'customers', ['customer_id'], ['id'])
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_selections_customer_id'), table_name='selections')
    op.drop_constraint(op.f('fk_selections_customer_id'), 'selections', type_='foreignkey')
    op.create_foreign_key(None, 'selections', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'selections', type_='foreignkey')
    op.create_foreign_key(op.f('fk_selections_customer_id'), 'selections', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_selections_customer_id'), 'selections', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'customer_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('fk_customer_sessions_customer_id'), 'customer_sessions', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_customer_sessions_customer_id'), 'customer_sessions', ['customer_id'], unique=False)
    op.drop_constraint(None, 'customer_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('customer_profiles_customer_id_fkey'), 'customer_profiles', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_customer_profiles_id'), table_name='customer_profiles')
    op.create_index(op.f('ix_customer_profiles_customer_id'), 'customer_profiles', ['customer_id'], unique=False)
    # ### end Alembic commands ###
