"""Add table_count to restaurants

Revision ID: cb1a80b8a402
Revises: 187e6978e7a5
Create Date: 2026-04-13 18:07:11.092932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb1a80b8a402'
down_revision: Union[str, Sequence[str], None] = '187e6978e7a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('table_count', sa.Integer(), nullable=False, server_default='10'))
    op.alter_column('restaurants', 'avg_price_range',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'avg_price_range',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('restaurants', 'table_count')
    # ### end Alembic commands ###
